name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # se ejecuta cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Publicar archivos en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # funciona automáticamente en repos públicos
          publish_dir: .           # publica desde la raíz del repo
          publish_branch: gh-pages # rama de publicación
          force_orphan: true       # evita conflictos de historial