name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # se ejecuta cada vez que hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo completo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # usa el token del Actions bot
          fetch-depth: 0            # necesario para historial completo

      # 2️⃣ Crear la rama gh-pages si no existe y publicar
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true  # fuerza una rama limpia
